<a href="https://colab.research.google.com/github/carloscelestino1/CursoDataScienceMachineLearning/blob/main/atividade1(segundo_modulo).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fuctura

1- Import o Numpy

2 - Utilize a função range do python para criar automaticamente uma lista de
números variando de 0 até 15.

3 - Converta a lista criada para um objeto do tipo numpy array.

4 - Crie um novo array equivalente ao anterior utilizando diretamente os
recursos do numpy.

5 - Crie um array de 10 zeros

6 - Crie um array de 10 números "um".

7 - Crie um array de 10 números "5"

8 - Crie um array de inteiros de 10 até 50

9 - Crie uma matriz identidade 3x3

In [1]:
# 1)
import numpy as np

In [4]:
# 2)
lista = list(range(0,16))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [8]:
# 3)
lista_array = np.array(lista)
lista_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
# 4)
array = np.array(range(0,16))
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
# 5)
array2 = np.array([0]*10)
array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# 6)
array3 = np.array(['um']*10)
array3

array(['um', 'um', 'um', 'um', 'um', 'um', 'um', 'um', 'um', 'um'],
      dtype='<U2')

In [24]:
# 7)
array4 = np.array([5]*10)
array4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [25]:
# 8)
array5 = np.array(range(10,51))
array5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [26]:
from numpy import *

In [28]:
# 9)
matriz = identity(3, dtype=int)
matriz

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])