<a href="https://colab.research.google.com/github/carloscelestino1/DataScience-and-ML/blob/main/aula2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]]

In [4]:
dados = np.matrix(data)
dados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [7]:
meusDados = np.matrix('1,2,3 ; 4,5,6 ; 7,8,9 ; 10,11,12')
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [8]:
pd.DataFrame(meusDados)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [9]:
meusDados

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [14]:
meuDf = pd.DataFrame(meusDados)

In [15]:
type(meuDf)

pandas.core.frame.DataFrame

In [16]:
meuDf.dtypes

0    int64
1    int64
2    int64
dtype: object

In [17]:
meuDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      int64
 1   1       4 non-null      int64
 2   2       4 non-null      int64
dtypes: int64(3)
memory usage: 224.0 bytes


In [19]:
meuDf.astype(float)

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [20]:
meuDf


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [21]:
meuDf = meuDf.astype(float) #modificar os tipos de dados

In [22]:
meuDf

0     1     2
0   1.0   2.0   3.0
1   4.0   5.0   6.0
2   7.0   8.0   9.0
3  10.0  11.0  12.0

In [25]:
meuDf[1] = meuDF[1].astype(str)
meuDF

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [26]:
meuDf.dtypes

0    float64
1     object
2    float64
dtype: object

In [29]:
meuDf.shape # tamanho total da tabela

(4, 3)

In [33]:
meuDf.head()

0   1     2
0   1.0   2   3.0
1   4.0   5   6.0
2   7.0   8   9.0
3  10.0  11  12.0

In [34]:
meuDf.head(2)

0  1    2
0  1.0  2  3.0
1  4.0  5  6.0

In [35]:
meuDf.tail()

0   1     2
0   1.0   2   3.0
1   4.0   5   6.0
2   7.0   8   9.0
3  10.0  11  12.0

In [36]:
meuDf.head(2)

0  1    2
0  1.0  2  3.0
1  4.0  5  6.0

In [37]:
meuDf.describe()

0          2
count   4.000000   4.000000
mean    5.500000   7.500000
std     3.872983   3.872983
min     1.000000   3.000000
25%     3.250000   5.250000
50%     5.500000   7.500000
75%     7.750000   9.750000
max    10.000000  12.000000

In [38]:
indice = ['Linha '+ str(i) for i in range(4)]

In [41]:
colunas = ['Coluna '+ str(i) for i in range(3)]

In [42]:
df2 = pd.DataFrame(data = meusDados, index = indice, columns = colunas)
df2

Coluna 0  Coluna 1  Coluna 2
Linha 0         1         2         3
Linha 1         4         5         6
Linha 2         7         8         9
Linha 3        10        11        12

In [43]:
df3 = {
    'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
    'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
    'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}
}
df3


{'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},
 'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
 'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}

In [46]:
df3 = pd.DataFrame(df3)

In [47]:
df4 = pd.concat([meuDf, df2, df3])

In [48]:
df4

0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0    2   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0    5   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0    8   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0   11  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN  NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN  NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN  NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN  NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN  NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN  NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN  NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
Linha 0      NaN  
Linha 1      NaN  
Linha 2      NaN  
Linha 3      NaN  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [49]:
df4.isnull()

0      1      2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0        False  False  False      True      True      True     True     True   
1        False  False  False      True      True      True     True     True   
2        False  False  False      True      True      True     True     True   
3        False  False  False      True      True      True     True     True   
Linha 0   True   True   True     False     False     False     True     True   
Linha 1   True   True   True     False     False     False     True     True   
Linha 2   True   True   True     False     False     False     True     True   
Linha 3   True   True   True     False     False     False     True     True   
Linha0    True   True   True      True      True      True    False    False   
Linha1    True   True   True      True      True      True    False    False   
Linha2    True   True   True      True      True      True    False    False   

         Coluna2  
0           True  
1           True  
2           True  
3           True  
Linha 0     True  
Linha 1     True  
Linha 2     True  
Linha 3     True  
Linha0     False  
Linha1     False  
Linha2     False

In [51]:
df4.isnull().sum()

0           7
1           7
2           7
Coluna 0    7
Coluna 1    7
Coluna 2    7
Coluna0     8
Coluna1     8
Coluna2     8
dtype: int64

In [52]:
df4.isnull().sum().sum()

66

In [53]:
df4.fillna

<bound method DataFrame.fillna of             0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0    2   3.0       NaN       NaN       NaN      NaN      NaN   
1         4.0    5   6.0       NaN       NaN       NaN      NaN      NaN   
2         7.0    8   9.0       NaN       NaN       NaN      NaN      NaN   
3        10.0   11  12.0       NaN       NaN       NaN      NaN      NaN   
Linha 0   NaN  NaN   NaN       1.0       2.0       3.0      NaN      NaN   
Linha 1   NaN  NaN   NaN       4.0       5.0       6.0      NaN      NaN   
Linha 2   NaN  NaN   NaN       7.0       8.0       9.0      NaN      NaN   
Linha 3   NaN  NaN   NaN      10.0      11.0      12.0      NaN      NaN   
Linha0    NaN  NaN   NaN       NaN       NaN       NaN      1.0      2.0   
Linha1    NaN  NaN   NaN       NaN       NaN       NaN      4.0      5.0   
Linha2    NaN  NaN   NaN       NaN       NaN       NaN      7.0      8.0   

         Coluna2  
0            NaN  
1            Na

In [54]:
df5 = df4.fillna(df4.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


In [55]:
df5

0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0    2   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0    5   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0    8   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0   11  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5  NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5  NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5  NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5  NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5  NaN   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5  NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5  NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [56]:
df8 = df5.copy()

In [57]:
df4.dropna(inplace=True)
df4

Empty DataFrame
Columns: [0, 1, 2, Coluna 0, Coluna 1, Coluna 2, Coluna0, Coluna1, Coluna2]
Index: []

In [58]:
df5

0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
0         1.0    2   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0    5   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0    8   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0   11  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5  NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5  NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5  NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5  NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha0    5.5  NaN   7.5       5.5       6.5       7.5      1.0      2.0   
Linha1    5.5  NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5  NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [59]:
df5.dropna(subset = [1], inplace = True)
df5

0   1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  Coluna2
0   1.0   2   3.0       5.5       6.5       7.5      4.0      5.0      6.0
1   4.0   5   6.0       5.5       6.5       7.5      4.0      5.0      6.0
2   7.0   8   9.0       5.5       6.5       7.5      4.0      5.0      6.0
3  10.0  11  12.0       5.5       6.5       7.5      4.0      5.0      6.0

In [61]:
df6 = df5.drop(columns = ['Coluna0'])
df6

0   1     2  Coluna 0  Coluna 1  Coluna 2  Coluna1  Coluna2
0   1.0   2   3.0       5.5       6.5       7.5      5.0      6.0
1   4.0   5   6.0       5.5       6.5       7.5      5.0      6.0
2   7.0   8   9.0       5.5       6.5       7.5      5.0      6.0
3  10.0  11  12.0       5.5       6.5       7.5      5.0      6.0

In [62]:
df7 = df6.drop(index = [2])
df7

0   1     2  Coluna 0  Coluna 1  Coluna 2  Coluna1  Coluna2
0   1.0   2   3.0       5.5       6.5       7.5      5.0      6.0
1   4.0   5   6.0       5.5       6.5       7.5      5.0      6.0
3  10.0  11  12.0       5.5       6.5       7.5      5.0      6.0

In [63]:
df5.Coluna2.unique()

array([6.])

In [64]:
df5.columns.unique()

Index([0, 1, 2, 'Coluna 0', 'Coluna 1', 'Coluna 2', 'Coluna0', 'Coluna1',
       'Coluna2'],
      dtype='object')

In [65]:
df5.index.unique()

Index([0, 1, 2, 3], dtype='object')

In [66]:
df8.sort_values(by = 'Coluna1')


0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  Coluna1  \
Linha0    5.5  NaN   7.5       5.5       6.5       7.5      1.0      2.0   
0         1.0    2   3.0       5.5       6.5       7.5      4.0      5.0   
1         4.0    5   6.0       5.5       6.5       7.5      4.0      5.0   
2         7.0    8   9.0       5.5       6.5       7.5      4.0      5.0   
3        10.0   11  12.0       5.5       6.5       7.5      4.0      5.0   
Linha 0   5.5  NaN   7.5       1.0       2.0       3.0      4.0      5.0   
Linha 1   5.5  NaN   7.5       4.0       5.0       6.0      4.0      5.0   
Linha 2   5.5  NaN   7.5       7.0       8.0       9.0      4.0      5.0   
Linha 3   5.5  NaN   7.5      10.0      11.0      12.0      4.0      5.0   
Linha1    5.5  NaN   7.5       5.5       6.5       7.5      4.0      5.0   
Linha2    5.5  NaN   7.5       5.5       6.5       7.5      7.0      8.0   

         Coluna2  
Linha0       3.0  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha1       6.0  
Linha2       9.0

In [69]:
df8.rename(columns = {'Coluna1':'COLUNA 1'}, inplace=True)
df8

0    1     2  Coluna 0  Coluna 1  Coluna 2  Coluna0  COLUNA 1  \
0         1.0    2   3.0       5.5       6.5       7.5      4.0       5.0   
1         4.0    5   6.0       5.5       6.5       7.5      4.0       5.0   
2         7.0    8   9.0       5.5       6.5       7.5      4.0       5.0   
3        10.0   11  12.0       5.5       6.5       7.5      4.0       5.0   
Linha 0   5.5  NaN   7.5       1.0       2.0       3.0      4.0       5.0   
Linha 1   5.5  NaN   7.5       4.0       5.0       6.0      4.0       5.0   
Linha 2   5.5  NaN   7.5       7.0       8.0       9.0      4.0       5.0   
Linha 3   5.5  NaN   7.5      10.0      11.0      12.0      4.0       5.0   
Linha0    5.5  NaN   7.5       5.5       6.5       7.5      1.0       2.0   
Linha1    5.5  NaN   7.5       5.5       6.5       7.5      4.0       5.0   
Linha2    5.5  NaN   7.5       5.5       6.5       7.5      7.0       8.0   

         Coluna2  
0            6.0  
1            6.0  
2            6.0  
3            6.0  
Linha 0      6.0  
Linha 1      6.0  
Linha 2      6.0  
Linha 3      6.0  
Linha0       3.0  
Linha1       6.0  
Linha2       9.0

In [75]:
df8.rename(columns = {0: "janeiro", 1: "fevereiro", 2: "março", 'Coluna 0': 'abril',
                      'Coluna 1': 'maio', 'Coluna 2': 'junho', 'Coluna0':'julho',
                      'COLUNA 1': 'agosto', 'setempro': 'setembro'}, inplace = True)
df8


janeiro fevereiro  março  abril  agosto  junho  julho  agosto  \
0            1.0         2    3.0    5.5     6.5    7.5    4.0     5.0   
1            4.0         5    6.0    5.5     6.5    7.5    4.0     5.0   
2            7.0         8    9.0    5.5     6.5    7.5    4.0     5.0   
3           10.0        11   12.0    5.5     6.5    7.5    4.0     5.0   
Linha 0      5.5       NaN    7.5    1.0     2.0    3.0    4.0     5.0   
Linha 1      5.5       NaN    7.5    4.0     5.0    6.0    4.0     5.0   
Linha 2      5.5       NaN    7.5    7.0     8.0    9.0    4.0     5.0   
Linha 3      5.5       NaN    7.5   10.0    11.0   12.0    4.0     5.0   
Linha0       5.5       NaN    7.5    5.5     6.5    7.5    1.0     2.0   
Linha1       5.5       NaN    7.5    5.5     6.5    7.5    4.0     5.0   
Linha2       5.5       NaN    7.5    5.5     6.5    7.5    7.0     8.0   

         setembro  
0             6.0  
1             6.0  
2             6.0  
3             6.0  
Linha 0       6.0  
Linha 1       6.0  
Linha 2       6.0  
Linha 3       6.0  
Linha0        3.0  
Linha1        6.0  
Linha2        9.0

In [76]:
df8.dropna(subset = ['fevereiro'], inplace = True)
df8

janeiro fevereiro  março  abril  agosto  junho  julho  agosto  setembro
0      1.0         2    3.0    5.5     6.5    7.5    4.0     5.0       6.0
1      4.0         5    6.0    5.5     6.5    7.5    4.0     5.0       6.0
2      7.0         8    9.0    5.5     6.5    7.5    4.0     5.0       6.0
3     10.0        11   12.0    5.5     6.5    7.5    4.0     5.0       6.0

In [79]:
df8.reset_index()

index  janeiro fevereiro  março  abril  agosto  junho  julho  agosto  \
0      0      1.0         2    3.0    5.5     6.5    7.5    4.0     5.0   
1      1      4.0         5    6.0    5.5     6.5    7.5    4.0     5.0   
2      2      7.0         8    9.0    5.5     6.5    7.5    4.0     5.0   
3      3     10.0        11   12.0    5.5     6.5    7.5    4.0     5.0   

   setembro  
0       6.0  
1       6.0  
2       6.0  
3       6.0

In [80]:
df9 = df8.rename(index = {
    0:'Elon Musk', 1: 'Bill Gates',
    2: 'Bernard Arnault', 3: 'Mark Zuckerberg'
})
df9

janeiro fevereiro  março  abril  agosto  junho  julho  \
Elon Musk            1.0         2    3.0    5.5     6.5    7.5    4.0   
Bill Gates           4.0         5    6.0    5.5     6.5    7.5    4.0   
Bernard Arnault      7.0         8    9.0    5.5     6.5    7.5    4.0   
Mark Zuckerberg     10.0        11   12.0    5.5     6.5    7.5    4.0   

                 agosto  setembro  
Elon Musk           5.0       6.0  
Bill Gates          5.0       6.0  
Bernard Arnault     5.0       6.0  
Mark Zuckerberg     5.0       6.0

In [81]:
df8.value_counts('março')

março
3.0     1
6.0     1
9.0     1
12.0    1
dtype: int64

In [82]:
df8.columns.value_counts().sum()

9

In [83]:
df8.index.value_counts().sum()

4